Update pr-issue-validator.yaml

diff --git a/.github/workflows/pr-issue-validator.yaml b/.github/workflows/pr-issue-validator.yaml
--- a/.github/workflows/pr-issue-validator.yaml
+++ b/.github/workflows/pr-issue-validator.yaml
@@ -43,7 +43,7 @@ jobs:
           echo "Skipping validation as this is a PR for documentation or chore."
           gh pr edit $PRNUM --remove-label "PR:Issue-verification-failed"
           gh pr edit $PRNUM --add-label "PR:Ready-to-Review"
-          exit 0
+          # exit 0
         fi
         
         ### For ex: Fixes #2123
@@ -80,7 +80,7 @@ jobs:
             echo "No Issue number detected hence failing the PR Validation check."
             gh pr edit $PRNUM --add-label "PR:Issue-verification-failed"
             gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
-            exit 1
+            # exit 1
         fi
 
         ### Here we are setting the Internal Field Separator to "/"
@@ -107,10 +107,10 @@ jobs:
             echo "Issue reference found in the pull request body."
             gh pr edit $PRNUM --remove-label "PR:Issue-verification-failed"
             gh pr edit $PRNUM --add-label "PR:Ready-to-Review"
-            exit 0
+            # exit 0
           else
             echo "Issue #$issue_num is not open"
-            exit 1
+            # exit 1
           fi
         else
             echo "Invalid Response Code obtained - error code: $response_code"
@@ -118,5 +118,55 @@ jobs:
             gh pr comment $PRNUM --body "PR is not linked to any issue, please make the corresponding changes in the body."
             gh pr edit $PRNUM --add-label "PR:Issue-verification-failed"
             gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
-            exit 1
+            # exit 1
         fi
+    
+    - name: Check SQL file format and duplicates
+      shell: bash
+      env: 
+          pr_no: ${{ github.event.pull_request.number }}
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+      run: |
+          echo "GitHub Token: $GH_TOKEN"
+          git fetch origin main
+          git diff origin/main...HEAD --name-only > mydiff
+          echo "Changed SQL files:"
+          cat mydiff
+          echo "==============="
+
+          file_list=$(git diff origin/main..HEAD --name-only | grep '^scripts/sql/')
+          echo "==============="
+
+          for filename in $file_list; do
+            echo "Checking File: $filename"
+            
+            if [[ "$filename" =~ \.(up|down)\.sql$ ]]; then
+              echo "File name is in the correct format: $filename"
+            else
+              echo "Error: File name is not in the correct format: $filename."
+              gh pr comment $pr_no --body "Error: The SQL file name is not in the correct format: $filename."
+              exit 1 
+            fi
+            echo "Current directory: $(pwd)"
+            
+            cd scripts/sql/
+            echo "SQL files directory: $(pwd)"
+            
+            migration_no=$(echo $filename | cut -d "/" -f 3 | cut -d "_" -f 1)
+            echo "Migration Number: $migration_no"
+            
+            migration_files_of_this_no=$(ls | grep -i $migration_no | wc -l)
+            cd ../../
+            echo "Current directory: $(pwd)"
+            
+            echo "Migration Number: $migration_no"
+            echo "Number of files with this migration number: $migration_files_of_this_no"
+            
+            if [[ $migration_files_of_this_no == "2" ]] ; then
+              echo "All looks good for this migration number."
+            else 
+               echo "Error: Migration number is repeated."
+               gh pr comment $pr_no --body "Error: The SQL file number is duplicated: $migration_no."
+               exit 1
+            fi
+          done
